@startuml blatt7
scale 2

title Blatt7.3

activate Kunde
activate Videotheke
Kunde ->  Videotheke: will ausleihen(Film, Guthaben)

alt Pwd prüfen
    Videotheke --> Videotheke : Guthaben prüfen

    alt Guthaben !== reicht aus
        Kunde <- Videotheke : Aufladen ermöglichen
    else
        Kunde <- Videotheke : Ausleihen success
    end
end

deactivate Kunde
deactivate Videotheke

' das Ausleihen eines Films nur bei vorhandenem
' Guthaben möglich sein soll. Sollte das Guthaben
' nicht ausreichen, ermöglichen Sie dem Nutzer das
' Aufladen seines Guthabens, indem Sie auf ein
' externes System verweisen, dass für eine geeignete
' Abbuchung zuständig ist

@endum